true ;;
false ;;
true && true ;;
true && false ;;
true || false ;;
false || false ;;
not true ;;
not false ;;
not (false || not false && not false) ;;
not (false || ((not false) && (not false))) ;;
2 < 3 ;;
2 < 3 && 2.0 >= 3.0 ;;
2 < 3 || 2.0 = 3.0 ;;
not (3 < 2) ;;
true > false ;;
false > true ;;
true > true ;;
